global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#igor_melnikov'
