plugin: gcp_compute
projects:
  - secret-project-name
filters: null
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].networkIP
keyed_groups:
  - key: labels
    separator: ""
scopes:
  - https://www.googleapis.com/auth/gcp-compute
service_account_file: ~/gcloud-service-key.json
auth_kind: serviceaccount
