---
- name: Deploy logging services
  hosts: "{{ target_host }}"
  become: true

  tasks:
    
    - name: Log into gitlab registry
      docker_login:
        registry: "{{ lookup('env', 'CI_REGISTRY') }}"
        username: "{{ lookup('env', 'CI_DEPLOY_USER') }}"
        password: "{{ lookup('env', 'CI_DEPLOY_PASSWORD') }}"

    - name: Create network
      docker_network:
        name: test

    - name: Deploy fluentd
      docker_container:
        name: fluentd
        image: "{{ lookup('env', 'CI_REGISTRY') }}/{{ lookup('env', 'CI_PROJECT_NAMESPACE') }}/fluentd:master"
        pull: yes
        recreate: yes
        ports:
          - "24224:24224/tcp"
          - "24224:24224/udp"
        networks:
          - name: test

    - name: Deploy elasticsearch
      docker_container:
        name: elasticsearch
        image: elasticsearch:6.5.4
        ports:
          - "9200:9200/tcp"
        networks:
          - name: test

    - name: Deploy kibana
      docker_container:
        name: kibana
        image: kibana:6.5.4
        ports:
          - "5601:5601"
        networks:
          - name: test
